UsingVueJSASP.NET/Controllers/VueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vue.DAL;
using Vue.Domain;

namespace UsingVueJSASP.NET.Controllers
{
    public class VueController : Controller
    {
        // GET: Vue
        UnitOfWork theWork;
        VueContext theContext;
        public VueController()
        {
            theContext = new VueContext();
            theWork = new UnitOfWork(theContext);
        }
        public ActionResult Index()
        {
            var getList = theWork.UserRepository.GetAll();
            return View(getList);
        }
      
        [HttpPost]
        public JsonResult GetUserList()
        {
            var getList = theWork.UserRepository.GetAll();
            return Json(getList, JsonRequestBehavior.AllowGet);
        }
  
        public ActionResult SignIn(int id)
        {
            var theAdminCheck = theWork.AdminRepository.GetById(id);
            if (theAdminCheck != null)
            {
                ViewBag.isAdmin = true;
            }
            else
            {
                ViewBag.isAdmin = false;
            }
            return View(id);
        }
        [HttpPost]
        public JsonResult GetUser(int id)
        {
            var getList = theWork.UserRepository.GetById(id);
            return Json(getList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Save(int id)
        {
            return View(id);
        }
        public ActionResult SaveToDb(Product theProduct)
        {

            theWork.ProductRepository.Add(theProduct);
            var test=theWork.complete();
            return View(test);
        }
    }
}

UsingVueJSASP.NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UsingVueJSASP.NET/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UsingVueJSASP.NET/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

UsingVueJSASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="border rounded-0 header-blue">
        <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Company Name</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#">Dropdown </a>
                            <div class="dropdown-menu"><a class="dropdown-item" href="#">First Item</a><a class="dropdown-item" href="#">Second Item</a><a class="dropdown-item" href="#">Third Item</a></div>
                        </li>
                    </ul>
                    <form class="form-inline mr-auto" target="_self">
                        <div class="form-group mb-0"><label for="search-field"><i class="fa fa-search"></i></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                    </form><span class="navbar-text"> <a class="login" href="#">Log In</a></span><a class="btn btn-light action-button" role="button" href="#">Sign Up</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

UsingVueJSASP.NET/Views/Vue/Index.cshtml
@using Vue.Domain
@{
    ViewBag.Title = "Index";
}
@model IEnumerable<User>

<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link href="~/Scripts/Style.css" rel="stylesheet" />
<script src="~/Scripts/vue.js"></script>
<script src="~/Scripts/vue.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-ellipse-progress/dist/vue-ellipse-progress.umd.min.js"></script>
<div class="container" id="app">
    <div id="app">
        <button v-on:click="show = !show">
            Toggle
        </button>
        <transition class="fade-enter-active" name="fade">
            <p v-if="show">hello</p>
        </transition>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card">

            <div class="card-header">
                <h3>Sígn In</h3>
                <div class="d-flex justify-content-end social_icon">
                    <span><i class="fab fa-facebook-square"></i></span>
                    <span><i class="fab fa-google-plus-square"></i></span>
                    <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">
                <form>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input id="user" type="text" class="form-control" placeholder="username">

                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input id="pass" type="password" class="form-control" placeholder="password">
                    </div>
                    <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div>
                    <div class="form-group" id="app">
                        <input type="button" v-on:click="checkIn" value="Login" class="btn float-right login_btn">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                this is footer
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

    });

    var app = new Vue({
        el: '#app',
        data: {
            UserData: [],
            show: true
        },
        methods: {
            checkIn: function () {
                var theTemp = this;
                var username = $('#user').val();
                var password = $('#pass').val();
                if (username == "" || password == "") {
                    alert("Username and Password must be more 0 charecter ");
                    return;
                }
                for (var i = 0; i < theTemp.UserData.length; i++) {
                    if (theTemp.UserData[i].usernaname == username && theTemp.UserData[i].password == password) {
                        window.location = "@Url.Action("SignIn", "Vue")?id=" + theTemp.UserData[i].Id;
                        return;
                    }
                }
                alert("Username or Password are wrong");
            }
        },
        created: function () {
            var ele = this;
                $.post("@Url.Action("GetUserList", "Vue", null)",
                    function (data, status, jqXHR) {
                        if (status == 'success')
                            ele.UserData = data;
                        else {

                        }
                }
                )
                    .done(function () {
                        console.log("Problem has been solved");
                    }).fail(function (error) {
                        console.log(error.ErrorMessage);
                    });
            //$.ajax(
            //    {
            //        url: '/vue/signın',
            //        datatype: 'json',
            //        method: 'post',
            //        success: function (data) {
            //            ele.userdata = data;
            //        },
            //        failure: function (response) {
            //            alert("res " + response.d);
            //        },
            //        error: function (hata, ajaxoptions, thrownerror) {
            //            alert(hata.status);
            //            alert(thrownerror);
            //            console.log(hata.responsetext);
            //        }
            //    }
            //);
            console.log("user eleent "+ele.UserData)

        }
    })

</script>

UsingVueJSASP.NET/Views/Vue/Save.cshtml
@using Vue.Domain
@{
    ViewBag.Title = "Save";
    var theProduct = new Product();
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<div class="alert alert-success hide" id="succes">
    <p
       >Product add succesfuly

    </p>
</div>
<div class="alert alert-danger hide" id="danger">
    <p>Something went wrong</p>
</div>
<div class="container text-info">
    <div class="row">
        <div class="col-md-3"><label class="col-form-label text-right">Product Name</label></div>
        <div  class="col-md-4 offset-md-0 align-content-center"><input id="pname" class="shadow-sm form-control-sm d-md-flex flex-fill align-items-end align-content-center" type="text"></div>
    </div>
    <div class="row">
        <div class="col-md-3"><label class="col-form-label text-right">Date</label></div>
        <div  class="col-md-4 offset-md-0 align-content-center"><input id="date" type="date"></div>
    </div>
    <div class="row">
        <div class="col-md-3"><label class="col-form-label text-right">Piece</label></div>
        <div  class="col-md-4 offset-md-0 align-content-center"><input id="piece" class="shadow-sm form-control-sm flex-fill align-content-center" type="number"></div>
    </div>
    <div class="row">
        <div class="col-md-3"><label class="col-form-label text-right">Price</label></div>
        <div class="col-md-4 offset-md-0 align-content-center"><input  id="price" class="shadow-sm form-control-sm flex-fill align-content-center" type="number"></div>
    </div>
    <div class="row" id="app">
        <div class="col-md-3"><label class="col-form-label text-right"></label></div>
        <div class="col-md-4 offset-md-0 align-content-center">
        <button id="saveBtn" class="btn btn-success btn-block btn-lg text-uppercase shadow-lg" style="width:167px; height:46px " v-on:click="save" type="button">
            <span class="hide spinner-border text-warning text-right" role="status" id="spinner"></span>
            <p id="text">Request</p>    
        </button>
        </div>
    </div>
</div>
<script src="~/Scripts/vue.js"></script>
<script src="~/Scripts/vue.min.js"></script>
<script>
    var app = new Vue({
        el: "#app",
        data: {

        },
        methods: {
            save: function () {
                var button = $("#saveBtn");
                
                var pname = $("#pname");
                var price = $("#price");
                var piece = $("#piece");
                var date = $("#date").val();
                var text = $("#text");
                $("#spinner").show();
                text.html("");
                console.log($("#date").val());
                if (pname.val() == "" || price.val() == "" || piece.val() == "" || date == "" ) {
                    alert("Problem have been found ");
                    text.html("Request");
                    $("#spinner").hide();
                    return;
                }
                var theProduct = @Html.Raw(Json.Encode(theProduct));
                theProduct.name = pname.val();
                theProduct.Date = date;
                theProduct.price = price.val();
                theProduct.piece = piece.val();
                theProduct.User_Id = '@Model';

                $.get("@Url.Action("SaveToDb", "Vue")", theProduct,
                    function (data, status) {
                    $("#succes").show();
                    setTimeout(function () { $("#succes").hide(); }, 3000);

                }).done(function () {
                    text.html("Request");
                    $("#spinner").hide();
                    setTimeout(function () { alert("Hello"); }, 3000);
                }).fail(function (xhr, ajaxOptions, thrownError) {
                    $("#danger").show();
                    setTimeout(function () { $("#danger").hide(); }, 3000);
                });
            }
        },
        created: function () {
            console.log("problem solved")
            $("#spinner").hide();
            $("#succes").hide();
            $("#danger").hide();
        }

    });

</script> 

UsingVueJSASP.NET/Views/Vue/SignIn.cshtml
@{
    ViewBag.Title = "SignIn";
    var isAdmin = ViewBag.isAdmin;
}
@model int

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/vue.js"></script>
<script src="~/Scripts/vue.min.js"></script>

<div class="nav navbar" id="app">
    <div class="nav-item align-baseline" id="app">
        <p v-if="isAdmin">{{userData.name}} {{userData.surname}} - Admin</p>
        <p v-else="isAdmin">{{userData.name}} {{userData.surname}} - User</p>

    </div>
    <div class="nav-item">
        <button class="btn btn-outline-dark" id="createButton" v-on:click="goto">Buy New Product</button>
    </div>
</div>
<div class="d-flex justify-content-center">
    <div class="card">
        <div class="card-header">
            Product List
        </div>
        <div class="card-body">
           <table class="table table-warning table-bordered d-xxl-table-cell">
               <tr>
                   <td>Product Name</td>
                   <td>Product Date</td>
                   <td>Price</td>
                   <td>Piece</td>
                   <td >#</td>
               </tr>
           </table>
        </div>
        <div class="card-footer">
            Deneme
        </div>
    </div>
</div>
        @section scripts{
    <script>
        var app = new Vue(
            {
                el: "#app",
                data: {
                    name: 'Yahya',
                    surname: '',
                    userData: {},
                    level: '',
                    isAdmin: '@isAdmin' =='True' ? true : false
                },
                methods: {
                    goto: function () {
                        window.location = "@Url.Action("Save", "Vue")?id=" + '@Model';
                    }
                },
                created:function () {
                        var theElement = this;
                        $.post("@Url.Action("GetUser", "Vue", new { id=@Model})",
                            function (data, status, jqXHR) {
                                if (status == 'success') {
                                    theElement.userData = data;
                                } else {

                                }
                            }

                            );
                         }

            }
        );
    </script>
}